# Sync Logic
# Remote Repo ---|pull|---> Local Repo(`.skills-repos/`) ---|copy|---> skills library(`skills-library/`, only skills)

# .skills-repos: ( path: `.skills-repos/<repoId>.zip` )
# e.g. [.skills-repos/vercel-labs/skills.zip, .skills-repos/obra/superpowers.zip]

# skills-library: ( path: `skills-library/<repoId>/<skill-path-parent>` )
# e.g. [skills-library/obra/superpowers/skills/brainstorming/, skills-library/anthropics/skills/pdf/]

# skills-mine: ( path: `skills-mine/<repoId>/<skill-path-parent>` )
# e.g. [skills-mine/obra/superpowers/skills/systematic-debugging/]

# skillDirPaths: `**/SKILL.md`

library:
- repoId: obra/superpowers
  repoType: github
  repoUrl: https://github.com/obra/superpowers.git
  skills:
    - name: brainstorming
      path: skills/brainstorming/SKILL.md
    - name: dispatching-parallel-agents
      path: skills/dispatching-parallel-agents/SKILL.md
    - name: executing-plans
      path: skills/executing-plans/SKILL.md
    - name: finishing-a-development-branch
      path: skills/finishing-a-development-branch/SKILL.md
    - name: receiving-code-review
      path: skills/receiving-code-review/SKILL.md
    - name: requesting-code-review
      path: skills/requesting-code-review/SKILL.md
    - name: subagent-driven-development
      path: skills/subagent-driven-development/SKILL.md
    - name: systematic-debugging
      path: skills/systematic-debugging/SKILL.md
    - name: test-driven-development
      path: skills/test-driven-development/SKILL.md
    - name: using-git-worktrees
      path: skills/using-git-worktrees/SKILL.md
    - name: using-superpowers
      path: skills/using-superpowers/SKILL.md
    - name: verification-before-completion
      path: skills/verification-before-completion/SKILL.md
    - name: writing-plans
      path: skills/writing-plans/SKILL.md
    - name: writing-skills
      path: skills/writing-skills/SKILL.md
- repoId: anthropics/skills
  repoType: github
  repoUrl: https://github.com/anthropics/skills.git
  skills:
    - name: pdf
      path: skills/pdf/SKILL.md
    - name: docx
      path: skills/docx/SKILL.md
    - name: pptx
      path: skills/pptx/SKILL.md
    - name: xlsx
      path: skills/xlsx/SKILL.md
- repoId: Lum1104/Understand-Anything
  repoType: github
  repoUrl: https://github.com/Lum1104/Understand-Anything.git
  skills:
    - name: understand-chat
      path: understand-anything-plugin/skills/understand-chat/SKILL.md
    - name: understand-dashboard
      path: understand-anything-plugin/skills/understand-dashboard/SKILL.md
- repoId: bradautomates/claude-video
  repoType: github
  repoUrl: https://github.com/bradautomates/claude-video.git
  skills:
    - name: claude-video
      path: SKILL.md

# skills library (`skills-library/`) & mine (`skills-mine/`) ---[absolute symbolic link]---> active workspace (`skills/`)
# e.g. [skills/sp-brainstorming -> skills-library/obra/superpowers/skills/brainstorming, skills/my-writing-plan -> skills-mine/obra/superpowers/skills/writing-plan]
workspace:
- repoId: obra/superpowers
  skills: 
  - name: brainstorming 
    source: obra/superpowers/skills/brainstorming
    target: sp-brainstorming 
  - name: executing-plans
    source: obra/superpowers/skills/executing-plans
    target: sp-executing-plans
- repoId: anthropics/skills
  skills: 
  - name: pdf
    source: anthropics/skills/skills/pdf
    target: anthropics-pdf
- repoId: bradautomates/claude-video
  skills:
  - name: claude-video
    source: bradautomates/claude-video
    target: claude-video

mine:
  - name: writing-plan
    source: obra/superpowers/skills/writing-plan   # skills-mine/obra/superpowers/skills/writing-plan
    target: my-writing-plan                        # skills/my-writing-plan 
